### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by IsmailM** [phenopolis/phenopolis_browser#63]
# internal error /individual/PH00018567/preview? 

```python
Traceback (most recent call last):
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/app/current/views/__init__.py", line 251, in decorated
    return f(*args, **kwargs)
  File "/var/app/current/views/individual.py", line 64, in individual
    ['Genes', [g for g in ind.get('genes','').split(',')]],
AttributeError: 'NoneType' object has no attribute 'split'
```

During handling of the above exception, another exception occurred:

```python
Traceback (most recent call last):
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "/var/app/current/views/__init__.py", line 159, in exceptions
    response = e.get_response()
AttributeError: 'AttributeError' object has no attribute 'get_response'
```

**Comment by pontikos** [comment]
This patient doesn't exist and I think issue resolved so closing issue.
